spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/export-import
    username: root
    password: Vivek@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update